# Generated by Django 3.1.1 on 2020-09-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='phnumber',
            field=models.IntegerField(default=1234567),
            preserve_default=False,
        ),
    ]