# Generated by Django 3.1.1 on 2020-09-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0002_text_phnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='phnumber',
            field=models.IntegerField(blank=True),
        ),
    ]