# Generated by Django 3.1.1 on 2020-09-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0003_auto_20200926_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='phnumber',
            field=models.CharField(max_length=1000),
        ),
    ]
